-- AlterTable
ALTER TABLE "CrosswordWord" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "GameRiddle" ADD COLUMN     "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
