"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { buildPlayerWordSearch } from "@/lib/wordsearch";
import { generateWordPool } from "@/lib/gameContent";
import { pickPlayerSet, createSeededRandom } from "@/lib/gameRandom";
import { CROSSWORD_WORDS_PER_LEVEL, WORD_SEARCH_SIZE_PER_LEVEL } from "@/lib/gameLevels";

export type CrosswordFormState = { error?: string; ok?: boolean };

export async function saveCrosswordWord(_prev: CrosswordFormState, formData: FormData): Promise<CrosswordFormState> {
  const id = String(formData.get("id") || "").trim();
  const level = Number(formData.get("level") || 1);
  const word = String(formData.get("word") || "").trim();
  const clue = String(formData.get("clue") || "").trim();
  const points = Number(formData.get("points") || 10);

  if (!word) return { error: "Word is required." };
  if (level < 1 || level > 3) return { error: "Level must be 1, 2, or 3." };

  if (id) {
    await prisma.crosswordWord.update({ where: { id }, data: { level, word, clue, points } });
  } else {
    const count = await prisma.crosswordWord.count({ where: { level } });
    await prisma.crosswordWord.create({ data: { level, word, clue, points, order: count } });
  }

  revalidatePath("/admin/games/crossword");
  return { ok: true };
}

export async function deleteCrosswordWord(id: string) {
  await prisma.crosswordWord.delete({ where: { id } });
  revalidatePath("/admin/games/crossword");
}

// Players never all see the same grid — each gets their own random subset
// of this level's word pool, hidden in their own grid (see /games/crossword).
// This just renders one random example so you can sanity-check the pool
// actually fits well; re-running it shows a different possible sample.
export async function previewSampleLayout(level: number): Promise<CrosswordFormState> {
  const words = await prisma.crosswordWord.findMany({ where: { level }, orderBy: { order: "asc" } });
  if (words.length === 0) {
    await prisma.crosswordLayout.deleteMany({ where: { level } });
    revalidatePath("/admin/games/crossword");
    return { error: "Add at least one word to this level first." };
  }

  const result = buildPlayerWordSearch(
    words.map((w) => ({ id: w.id, word: w.word, clue: w.clue, points: w.points })),
    `admin-preview:${Date.now()}:${Math.random()}`,
    CROSSWORD_WORDS_PER_LEVEL[level],
    WORD_SEARCH_SIZE_PER_LEVEL[level],
    pickPlayerSet,
    createSeededRandom
  );

  await prisma.crosswordLayout.upsert({
    where: { level },
    update: { width: result.size, height: result.size, placements: { grid: result.grid, words: result.placements }, unplaced: result.unplaced },
    create: { level, width: result.size, height: result.size, placements: { grid: result.grid, words: result.placements }, unplaced: result.unplaced },
  });

  revalidatePath("/admin/games/crossword");

  if (result.unplaced.length > 0) {
    return { error: `This sample couldn't fit: ${result.unplaced.join(", ")}. If that keeps happening, those words may be too long for the grid, or the pool is too small.` };
  }
  return { ok: true };
}

export async function generateWordsForLevel(level: number): Promise<CrosswordFormState> {
  const pool = await generateWordPool(level);
  if (pool.length === 0) {
    return { error: "Nothing to generate from yet — add speakers, sponsors, or a convener note first." };
  }

  await prisma.$transaction([
    prisma.crosswordWord.deleteMany({ where: { level, autoGenerated: true } }),
    prisma.crosswordWord.createMany({
      data: pool.map((w, i) => ({ level, word: w.word, clue: w.clue, points: w.points, order: 1000 + i, autoGenerated: true })),
    }),
  ]);

  revalidatePath("/admin/games/crossword");
  return { ok: true };
}
